TRUNCATE TABLE routines CASCADE;

INSERT INTO routines (id, title, level, session, thumbnail) VALUES (1, 'Flow Through Switzerland',  'Advanced', 'Morning', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDq7mrLLsOeNdP-S7_ULkQ3SxDUPK2ulMKN-Py6frIiWS0c66D32ZWNYyBr2P_a-5dIsB4P-pL5NMDr7g-huKgJogxYKjDuJZ574CygrPXWr8A_qA_M12ipXWU6txl9Dc63BuWwjUflk3ai6iXcu6eYMB1VVP6oO-oPvvKbXiQ/');

INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Mountain Hands In Prayer', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDcQXN_21QTJhIapBgaPcO3vhEAeqg_I4kqa2Tve-AqkYml5fho-GalZ6OH5jD_Ixd2xutXcBqr__MPVl5dv53ux1uJq3koYlyXZUq2sRLhdRHSLwi_D1Q60oaCMnPyCwWIkyFZZjjtm7C3OPrJU_45PF-uHf7KcF62Zn78WOg/', '10000', 'Mountain Hands In Prayer', 'SHAFUDIN JAYA (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Right Knee To Chest', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtuE_ht-MgVBjVXnDO1h18FSULiXts1KRfeblJ_bhNhpnnVoXYM5zYogUiO1BjhjYJvbvGbvZPH7fOt7ANbInsG_OzO3FwyNA-JNo4Jca0KmwG8OkYuHZOr4b2IFsspafymzHtnCwjxaiM0Ex62IcUFSyrZMqen5WlfWivOKQ/', '10000', 'Right Knee To Chest', 'ROMANBURRI PHOTOGRAPHY (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Left Knee To Chest', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDth4jOkbbBbVg_OVhRaI4GCzCQqrZ9foypis2kMA-Wya_V_lt6fqTAwMfN2udDHurCxJ_j4C0yW19XxvLgCik2McuhbnXPnaUT-tgrcK5QW30GKk0mo2_AzqeOc8z7-bE1G7XtMDemft8cQ99CFyYuwDkaLN_Zq5KXAyYFnPQ/', '10000', 'Left Knee To Chest', 'MARC HENAUER (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Forward Fold', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDq7mrLLsOeNdP-S7_ULkQ3SxDUPK2ulMKN-Py6frIiWS0c66D32ZWNYyBr2P_a-5dIsB4P-pL5NMDr7g-huKgJogxYKjDuJZ574CygrPXWr8A_qA_M12ipXWU6txl9Dc63BuWwjUflk3ai6iXcu6eYMB1VVP6oO-oPvvKbXiQ/', '10000', 'Forward Fold', 'LIANA MANUKYAN (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Hand Under Foot', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtuFC6AudPXsTm6KLmp_-UJnyO4KywLTK4ZBHDNWYlusbkMMamUVD1LZXsvYNwI1792G_4KV_NCHhEQ8kHnJEIfs0hOB6ljunCtd-Ur5egcB_Gi8atxUbUtOVwU7NJvhrsX99-Qchf5xtKMgPHZYhIUw7d8_tT8UPk_NObREvPU/', '10000', 'Hand Under Foot', 'ANTHONY LEUTENEGGER (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Raised Hands', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDttNrX1K7gkIft7EwTU8oXDm4hKV46_78pcykxaH1G2bihHwc9YWge6jDUOimTCeGCt_RwCep8HK25DMe2tTnvHcZPdOUWTcY--OI9FvDAjPusg9uSmiZdkUg-RNTJU6UiDoQh9-9cXbLTneCWV2uwJlElNZPkSWB9sGAjwSrCU/', '10000', 'Raised Hands', 'KAROL NIENARTOWICZ (source: NatGeo)', 1);


-- Mindful Mediterranean --
INSERT INTO routines (id, title, level, session, thumbnail) VALUES (1, 'Mindful Mediterranean',  'Beginner', 'Morning', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDGP47aetJ9ky65z6mkVeNkvZykGoQeB1aXZ9u6GRHQAOjWewS8T9fGAqz5oiXopvcTCn1fW0SRk5T8wtFE_OoShUuLE964H90ztWxg1CIJsP_-C-miiqDF2Ldg64YOsSzMMxzQE7nwfTGZIQ38N39M9U_tcgBUYqVk/');

INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (1, 'Mountain Hands In Prayer', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/sunset-cagliari-sardinia-italy.adapt.945.1.jpg', 125000, 'Mountain Hands In Prayer', 'RSFOTOGRAPHY/GETTY IMAGES (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (2, 'Raised Hands', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtvckriPEm1v0xPX7hQ_7re5XBXm6JPyUMuiWN8K1-4CseqqL6YzPLUyzEr8VXMDsvth_ptkTWP33654EPJuQ5Xee7tdfqCZZ65pSyDu4u2aOCshXEgOvsj1QBo4VFWlHU3Ff6wTEOli87s3qIetAAn3YDQyJ3G4idYUY6v/',125000, 'Raised Hands', ' ZSUZSANNA ACS, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (3, 'Standing Backbend', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/cafe-sidi-bou-said-tunisia.adapt.676.1.jpg', 125000, 'Standing Backbend', 'MAX SHEN, GETTY IMAGES (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (4, 'Low Lunge', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/harbor-cathedral-palma-mallorca-spain.adapt.945.1.jpg', 125000, 'Low Lunge', 'ROBERT HARDING/ALAMY STOCK PHOTO (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (5, 'Lunge', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/cafe-sidi-bou-said-tunisia.adapt.945.1.jpg', 125000, 'Lunge', 'MAX SHEN, GETTY IMAGES (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (6, 'Warrior One', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDNd_NDDvcf6w_r8guXojs6p9893PDHC7tJyIsuJG30q3FXe5yAKJVT4H5qUThUgWKVtvWWz6-imR9rTl3IktEZz76Ldde0GbohCSWsu2k0LEUyYZeb2V-UwVs8I-VfuM3ZERMpQHWbf0dFxcCUZG3yE0L_Zb-cY19v1PM-h/', 125000, 'Warrior One', 'WAEL MASSALKHI, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (7, 'Warrior Two', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDYlFhyjn9GOK1WjSayJa-8R6Tu4P6No6l3Hpch7qUNaMYtlENpmKFpl7n-YbxAes6RNgRFP62WxwUgcpZZmEt8qSAemadErrSJFY3D0PUb6z8OJ0Xw24o4YsVNauQESGSr87-1aZDg0AWvmU9ErE1UICKvIGEm9_JIfn_e98J0/', 125000, 'Warrior Two', 'AMIN HAZINII, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (8, 'Humble Warrior', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDYjTTVT_iRhNLNA4RNCYZMwVxFgcS6vcTqQbM5I9MV62BD0dehy-ZKzrJzu2lNIeVUbkjBQimEQty1kVnEyHf8L3wkfrtgxBKZILNCBaiDq8s-mimKyMlnq6HfggSIG1KIQWwgaxHEvu0i-c6bKjQ0OvWKDWFlY1yEdoxton7A/', 125000, 'Humble Warrior', 'YIANNIS PAVLIS, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (9, 'Extended Side Angle', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDGLXOXWoMOlvMLj5pqMNEInR0fJ30e44Bjfw1rMzBCeOhgag27sNqkVdpEiDEZHG1mXphEuH4aHjwOVAqA11TXh9u5g7geTgszAfSo3C9aajZGWg8e0h8GwIGceK-PulX2LGVPA-eLwNrDcKu0c-Ky8v0syCYgXDpaaEhOvzA/', 125000, 'Extended Side Angle', 'ANDREA MARINELLI, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (10, 'Bound Side Angle', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDYhpGtnqDRuOIqVnyxh1j23H0_aQCFDs2dY1sMtvVfvaFEanO6oHNiu-36dtoLhRDKAb15OEnI0ObkjjtQrvoSCCiV_fJb21T5HgL_zrSZ6nYjmBrulnG5S-Zz8BEn8-7Srmh-4qY00FWmPZ4jRU-gOD1zfDvVXjULQXV88CO4/', 125000, 'Bound Side Angle', 'RAUL BOTELLO, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (11, 'Extended Triangle', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDCxpaqguqywr1Xqb54mNolYLDivt1ypqDMxw3J20xqQ4QnzcVame8J7xESffpjreommt0GD2g15_w6yEs7LeODFYrydG1ks9rvOhcOaDd1GzcG9xcOudb-orDe7oruAww-3O9uYbOPc4Pr2ya2mLL7igxX3Tkp9qkOZOeXi6iA/', 125000, 'Extended Triangle', 'CATIE FRECH, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (12, 'Bound Triangle', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDcXlI3qGVSHigZNNas5ox2pCDUzaBMLHN8wfTJsYJfOMIwWmlppwl37qI6KXDunRjrN8XNWxbLEc4eq7C1FmtbDqydIX1KjBtQ2oT6TpPSZC55rR1HmAPnk-KerxlRUV-IkbCIOM2dWIhL_DR5cqfaTC7LUevcFIADhRw/', 125000, 'Bound Triangle', 'ALLYSON FERNANDEZ, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (13, 'Half Moon', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDGP47aetJ9ky65z6mkVeNkvZykGoQeB1aXZ9u6GRHQAOjWewS8T9fGAqz5oiXopvcTCn1fW0SRk5T8wtFE_OoShUuLE964H90ztWxg1CIJsP_-C-miiqDF2Ldg64YOsSzMMxzQE7nwfTGZIQ38N39M9U_tcgBUYqVk/', 125000, 'Half Moon', 'KRZYSZTOF LORANT, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (14, 'Warrior Three', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDGGXmnJDXq9HcEKEOkM_wGdDkJskgDgjZlzrkgU5GL4zmB8f6Gjwej4TBbDdZ6_8ORL_UBGkIxpF0RMC3XL10x1H0jr4eOC0OvJFiE7Wh8Mot1-7yU6SGBF0nEvPHi_cMD-GvNYyw3Yet59LLE63fAaYYXp5LOWL1KW/', 125000, 'Warrior Three', 'CRAIG JENSEN, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (15, 'Tip Toe', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDUYbBbM9pZMGbkQoGOkj04Vz8_jKs7JEfSYS7F2gVdfDxGHolSmE2LHBPF2y3FFCnspLK1oFKG-KZbRErt1qqwRfok7xqeNkdTv26rCXA1BVnmCQ9s5hNqfyEY9vOoCGbxpRFOg-nYTtqmD7yHiRgKZWa_MFRYNKIAhiXPO/', 125000, 'Tip Toe', 'IAN JUDD, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (16, 'Two-Hands Foot', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtrDlknmXGIBa_t3KFjqldh0eGmGySoIgR7VBMSdbYITtaPizMWP4B5zwpyvaY_ylTHT51l9XbuHhrrXYJ341GgMKQKBIwX3C4PZo3th-Pqm-pBuF6W1UhXifFGoF4wmJijTaZ1NMYkWteMy5tkSE4_UwHsoLtUIpMbUx7t/', 125000, 'Tip Toe', 'ADRIAN ROBERT NANUT, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (17, 'Extended One-Foot', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDNeYpbUrn9lxJwsGhs2YY1_NdCiuTZAMGIS3O5edTHcLNnfuzOQ0uJPBM80RftTtOCe0NsVOP2B1XeVaacA756mPz50v_Wy2MY_hdnnYNxhtBwlfY0M88XdNuQaG7xEedlX5VniR21q19u-ZrOXj4fAp9AZp6eGi51i1w/', 125000, 'Extended One-Foot', 'LOU EPPELSHEIMER, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (18, 'Extended Hand-To-Big-Toe', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtoRKvlO3WKVONPtCWRO7bsjA0c-T_ozGEPn7LAsJ3wcrTQzq8OTtRnbA2xu8t8EqgdIV6vxYDtCJY9mhMV5Re8mnhqepqmFrGM2vs7S9OLU3Oy7KUQEG7NQYT8_I4E6NpzJZor4XIF9yhbCIr-inOTp_AtY54KqXI/', 125000, 'Extended Hand-To-Big-Toe', 'VIRGIL CHEUNG, YOUR SHOT (source: NatGeo)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (19, 'Tree', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDC5vX0OmrIKb8hMp2VcN_YmCndwW9G6jPMvKTrZ1rMo2VEo1UvQiHWP1KjA-hBsBzIvM-Ew0nNwdB5T5dA36v8zN2VbovNE49qjEkobeD3x02n6qoLpCsJm_6n1-bfGJ8nSAFb9AYNr8eXIHXlaBeUW2SDLRL-2TAemxNtj/', 125000, 'Tree', 'JOVAN NIKOLIC, YOUR SHOT (source: NatGeo)', 1);
