TRUNCATE TABLE routines CASCADE;

INSERT INTO routines (id, title, level, session, thumbnail) VALUES (1, 'Flow Through Switzerland',  'Advanced', 'Morning', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDq7mrLLsOeNdP-S7_ULkQ3SxDUPK2ulMKN-Py6frIiWS0c66D32ZWNYyBr2P_a-5dIsB4P-pL5NMDr7g-huKgJogxYKjDuJZ574CygrPXWr8A_qA_M12ipXWU6txl9Dc63BuWwjUflk3ai6iXcu6eYMB1VVP6oO-oPvvKbXiQ/');

INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Mountain Hands In Prayer', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDcQXN_21QTJhIapBgaPcO3vhEAeqg_I4kqa2Tve-AqkYml5fho-GalZ6OH5jD_Ixd2xutXcBqr__MPVl5dv53ux1uJq3koYlyXZUq2sRLhdRHSLwi_D1Q60oaCMnPyCwWIkyFZZjjtm7C3OPrJU_45PF-uHf7KcF62Zn78WOg/', '10000', 'Mountain Hands In Prayer', 'SHAFUDIN JAYA (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Right Knee To Chest', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtuE_ht-MgVBjVXnDO1h18FSULiXts1KRfeblJ_bhNhpnnVoXYM5zYogUiO1BjhjYJvbvGbvZPH7fOt7ANbInsG_OzO3FwyNA-JNo4Jca0KmwG8OkYuHZOr4b2IFsspafymzHtnCwjxaiM0Ex62IcUFSyrZMqen5WlfWivOKQ/', '10000', 'Right Knee To Chest', 'ROMANBURRI PHOTOGRAPHY (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Left Knee To Chest', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDth4jOkbbBbVg_OVhRaI4GCzCQqrZ9foypis2kMA-Wya_V_lt6fqTAwMfN2udDHurCxJ_j4C0yW19XxvLgCik2McuhbnXPnaUT-tgrcK5QW30GKk0mo2_AzqeOc8z7-bE1G7XtMDemft8cQ99CFyYuwDkaLN_Zq5KXAyYFnPQ/', '10000', 'Left Knee To Chest', 'MARC HENAUER (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Forward Fold', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDq7mrLLsOeNdP-S7_ULkQ3SxDUPK2ulMKN-Py6frIiWS0c66D32ZWNYyBr2P_a-5dIsB4P-pL5NMDr7g-huKgJogxYKjDuJZ574CygrPXWr8A_qA_M12ipXWU6txl9Dc63BuWwjUflk3ai6iXcu6eYMB1VVP6oO-oPvvKbXiQ/', '10000', 'Forward Fold', 'LIANA MANUKYAN (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Hand Under Foot', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtuFC6AudPXsTm6KLmp_-UJnyO4KywLTK4ZBHDNWYlusbkMMamUVD1LZXsvYNwI1792G_4KV_NCHhEQ8kHnJEIfs0hOB6ljunCtd-Ur5egcB_Gi8atxUbUtOVwU7NJvhrsX99-Qchf5xtKMgPHZYhIUw7d8_tT8UPk_NObREvPU/', '10000', 'Hand Under Foot', 'ANTHONY LEUTENEGGER (source: NatGeo)', 1);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Raised Hands', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDttNrX1K7gkIft7EwTU8oXDm4hKV46_78pcykxaH1G2bihHwc9YWge6jDUOimTCeGCt_RwCep8HK25DMe2tTnvHcZPdOUWTcY--OI9FvDAjPusg9uSmiZdkUg-RNTJU6UiDoQh9-9cXbLTneCWV2uwJlElNZPkSWB9sGAjwSrCU/', '10000', 'Raised Hands', 'KAROL NIENARTOWICZ (source: NatGeo)', 1);


INSERT INTO routines (id, title, level, session, thumbnail) VALUES (2, 'Mindful Mediterranean',  'Beginner', 'Morning', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/cafe-sidi-bou-said-tunisia.adapt.945.1.jpg');

INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Mountain Hands In Prayer', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/sunset-cagliari-sardinia-italy.adapt.945.1.jpg', '30000', 'Mountain Hands In Prayer', 'RSFOTOGRAPHY/GETTY IMAGES (source: NatGeo)', 2);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Raised Hands', 'http://www.nationalgeographic.com/travel/lists/underrated-mediterranean-destinations/#/windmills-trapani-sicily-italy.jpg', '30000', 'Raised Hands', 'PHOTOGRAPH BY MAXICS, GETTY IMAGES (source: NatGeo)', 2);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Standing Backbend', 'http://www.nationalgeographic.com/travel/lists/underrated-mediterranean-destinations/#/science-museum-valencia-spain.jpg', '30000', 'Standing Backbend', 'JULIAN ELLIOTT, GETTY IMAGES (source: NatGeo)', 2);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Revolved Chair Open Arms', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/harbor-cathedral-palma-mallorca-spain.adapt.945.1.jpg', '30000', 'Revolved Chair Open Arms', 'ROBERT HARDING/ALAMY STOCK PHOTO (source: NatGeo)', 2);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('One-Leg Chair', 'http://www.nationalgeographic.com/travel/lists/underrated-mediterranean-destinations/#/cafe-sidi-bou-said-tunisia.jpg', '30000', 'One-Leg Chair', 'MAX SHEN, GETTY IMAGES (source: NatGeo)', 2);
INSERT INTO moves (name, image, milliseconds, audio, image_credit, routine_id) VALUES ('Revolved One-Leg Chair', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/street-tunis-tunisia.adapt.768.1.jpg', '30000', 'Revolved One-Leg Chair', 'NICOLAS FAUQUÉ, GETTY IMAGES (source: NatGeo)', 2);
