TRUNCATE TABLE routines CASCADE;
-- -- Flow with Sia / Song: Cheap Thrills

INSERT INTO routines (id, title, level, session, thumbnail) VALUES (1, 'Cheap Thrills',  'Beginner', 'Evening', 'https://yoga.com/media/poses/photo/src/ha/half-boat-pose.jpg');

INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (1, 'Tree Pose', 'https://yoga.com/media/poses/photo/src/tr/tree-pose-left-foot-in-front-of-thigh.jpg', 20777, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: yoga.com)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (2, 'Crane', 'https://yoga.com/media/poses/photo/src/cr/crane-pose.jpg', 20777, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: yoga.com)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (3, 'Half Boat Pose', 'https://yoga.com/media/poses/photo/src/ha/half-boat-pose.jpg', 20777, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: yoga.com)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (4, 'Upward Table Pose', 'https://yoga.com/media/poses/photo/src/up/upward-table-pose.jpg', 20777, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: yoga.com)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (5, 'Plank Pose', 'https://yoga.com/media/cache/46/db/46db2a6a405993b13b9aab48c428f9a6.jpg', 20777, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: yoga.com)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (6, 'Eagle Pose', 'https://yoga.com/media/poses/photo/src/ea/eagle-pose-right.jpg', 20777, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: yoga.com)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (7, 'Half Side Plank Pose', 'https://yoga.com/media/poses/photo/src/ha/half-side-plank-pose-on-right-hand.jpg', 20777, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: yoga.com)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (8, 'Side Plank Pose', 'https://yoga.com/media/poses/photo/src/si/side-plank-pose-left-leg-up.jpg', 20777, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: yoga.com)', 1);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (9, 'Horse Face Pose', 'https://yoga.com/media/poses/photo/src/ho/horse-face-pose-right.jpgg', 20777, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: yoga.com)', 1);

-- - Wake-Up-Call / Song: Avicii --
INSERT INTO routines (id, title, level, session, thumbnail) VALUES (2, 'WAKE ME UP',  'Beginner', 'Morning', 'https://yoga.com/media/poses/photo/src/up/upward-plank-pose.jpg');


INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (10, 'Downward Dog', 'https://yoga.com/media/cache/e1/6c/e16c631aef1903c2e87570323b2e12fe.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (11, 'Upward Plank', 'https://yoga.com/media/poses/photo/src/up/upward-plank-pose.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (12, 'Low Lunge', 'https://yoga.com/media/poses/photo/src/lo/low-lunge-left-leg-straight.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (13, 'Right Triangle', 'https://yoga.com/media/cache/43/2c/432c86b349511628ddf4cecbb764a49d.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (14, 'Bow Pose', 'https://yoga.com/media/poses/photo/src/bo/bow-pose.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (15, 'Easy Plow Pose', 'https://yoga.com/media/cache/97/b1/97b13ac4e5a0a93e9de4dcfd0528536d.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (16, 'Mountain Pose', 'https://yoga.com/media/cache/10/b0/10b06c949d83ff46d2185b88e72d9b30.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (17, 'Tree Pose', 'http://yogagloble.com/img/720ee90e188c4e4ac35f8b332f904c8d.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);


-- Mindful Mediterranean / Song: Love Me Now --Dropped
INSERT INTO routines (id, title, level, session, thumbnail) VALUES (3, 'MEDITERRANEAN MEDLY ',  'EXPERT', 'Morning', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDGP47aetJ9ky65z6mkVeNkvZykGoQeB1aXZ9u6GRHQAOjWewS8T9fGAqz5oiXopvcTCn1fW0SRk5T8wtFE_OoShUuLE964H90ztWxg1CIJsP_-C-miiqDF2Ldg64YOsSzMMxzQE7nwfTGZIQ38N39M9U_tcgBUYqVk/');

INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (18, 'Mountain Hands In Prayer', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDGP47aetJ9ky65z6mkVeNkvZykGoQeB1aXZ9u6GRHQAOjWewS8T9fGAqz5oiXopvcTCn1fW0SRk5T8wtFE_OoShUuLE964H90ztWxg1CIJsP_-C-miiqDF2Ldg64YOsSzMMxzQE7nwfTGZIQ38N39M9U_tcgBUYqVk/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'RSFOTOGRAPHY/GETTY IMAGES (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (19, 'Low Lunge', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/harbor-cathedral-palma-mallorca-spain.adapt.945.1.jpg', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'ROBERT HARDING/ALAMY STOCK PHOTO (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (20, 'Lunge', 'http://www.nationalgeographic.com/content/dam/travel/2017-digital/underrated-mediterranean-destinations/cafe-sidi-bou-said-tunisia.adapt.945.1.jpg', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'MAX SHEN, GETTY IMAGES (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (21, 'Warrior One', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDYlFhyjn9GOK1WjSayJa-8R6Tu4P6No6l3Hpch7qUNaMYtlENpmKFpl7n-YbxAes6RNgRFP62WxwUgcpZZmEt8qSAemadErrSJFY3D0PUb6z8OJ0Xw24o4YsVNauQESGSr87-1aZDg0AWvmU9ErE1UICKvIGEm9_JIfn_e98J0/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'AMIN HAZINII, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (22, 'Humble Warrior', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDYjTTVT_iRhNLNA4RNCYZMwVxFgcS6vcTqQbM5I9MV62BD0dehy-ZKzrJzu2lNIeVUbkjBQimEQty1kVnEyHf8L3wkfrtgxBKZILNCBaiDq8s-mimKyMlnq6HfggSIG1KIQWwgaxHEvu0i-c6bKjQ0OvWKDWFlY1yEdoxton7A/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'YIANNIS PAVLIS, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (23, 'Bound Side Angle', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDYhpGtnqDRuOIqVnyxh1j23H0_aQCFDs2dY1sMtvVfvaFEanO6oHNiu-36dtoLhRDKAb15OEnI0ObkjjtQrvoSCCiV_fJb21T5HgL_zrSZ6nYjmBrulnG5S-Zz8BEn8-7Srmh-4qY00FWmPZ4jRU-gOD1zfDvVXjULQXV88CO4/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'RAUL BOTELLO, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (24, 'Extended Triangle', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDCxpaqguqywr1Xqb54mNolYLDivt1ypqDMxw3J20xqQ4QnzcVame8J7xESffpjreommt0GD2g15_w6yEs7LeODFYrydG1ks9rvOhcOaDd1GzcG9xcOudb-orDe7oruAww-3O9uYbOPc4Pr2ya2mLL7igxX3Tkp9qkOZOeXi6iA/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'CATIE FRECH, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (25, 'Bound Triangle', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDcXlI3qGVSHigZNNas5ox2pCDUzaBMLHN8wfTJsYJfOMIwWmlppwl37qI6KXDunRjrN8XNWxbLEc4eq7C1FmtbDqydIX1KjBtQ2oT6TpPSZC55rR1HmAPnk-KerxlRUV-IkbCIOM2dWIhL_DR5cqfaTC7LUevcFIADhRw/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'ALLYSON FERNANDEZ, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (26, 'Half Moon', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDGP47aetJ9ky65z6mkVeNkvZykGoQeB1aXZ9u6GRHQAOjWewS8T9fGAqz5oiXopvcTCn1fW0SRk5T8wtFE_OoShUuLE964H90ztWxg1CIJsP_-C-miiqDF2Ldg64YOsSzMMxzQE7nwfTGZIQ38N39M9U_tcgBUYqVk/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'KRZYSZTOF LORANT, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (27, 'Tip Toe', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDUYbBbM9pZMGbkQoGOkj04Vz8_jKs7JEfSYS7F2gVdfDxGHolSmE2LHBPF2y3FFCnspLK1oFKG-KZbRErt1qqwRfok7xqeNkdTv26rCXA1BVnmCQ9s5hNqfyEY9vOoCGbxpRFOg-nYTtqmD7yHiRgKZWa_MFRYNKIAhiXPO/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'IAN JUDD, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (28, 'Two-Hands Foot', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtrDlknmXGIBa_t3KFjqldh0eGmGySoIgR7VBMSdbYITtaPizMWP4B5zwpyvaY_ylTHT51l9XbuHhrrXYJ341GgMKQKBIwX3C4PZo3th-Pqm-pBuF6W1UhXifFGoF4wmJijTaZ1NMYkWteMy5tkSE4_UwHsoLtUIpMbUx7t/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'ADRIAN ROBERT NANUT, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (29, 'Extended One-Foot', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDNeYpbUrn9lxJwsGhs2YY1_NdCiuTZAMGIS3O5edTHcLNnfuzOQ0uJPBM80RftTtOCe0NsVOP2B1XeVaacA756mPz50v_Wy2MY_hdnnYNxhtBwlfY0M88XdNuQaG7xEedlX5VniR21q19u-ZrOXj4fAp9AZp6eGi51i1w/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'LOU EPPELSHEIMER, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (30, 'Extended Hand-To-Big-Toe', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtoRKvlO3WKVONPtCWRO7bsjA0c-T_ozGEPn7LAsJ3wcrTQzq8OTtRnbA2xu8t8EqgdIV6vxYDtCJY9mhMV5Re8mnhqepqmFrGM2vs7S9OLU3Oy7KUQEG7NQYT8_I4E6NpzJZor4XIF9yhbCIr-inOTp_AtY54KqXI/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'VIRGIL CHEUNG, YOUR SHOT (source: NatGeo)', 3);
INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (31, 'Tree', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDC5vX0OmrIKb8hMp2VcN_YmCndwW9G6jPMvKTrZ1rMo2VEo1UvQiHWP1KjA-hBsBzIvM-Ew0nNwdB5T5dA36v8zN2VbovNE49qjEkobeD3x02n6qoLpCsJm_6n1-bfGJ8nSAFb9AYNr8eXIHXlaBeUW2SDLRL-2TAemxNtj/', 17142, 'https://soundcloud.com/hundredwaters/show-me-love-skrillex-remix-ft-chance-the-rapper-moses-sumney-robin-hannibal', 'JOVAN NIKOLIC, YOUR SHOT (source: NatGeo)', 3);









-- - Wake-Up-Call / Song: Avicii --
-- INSERT INTO routines (id, title, level, session, thumbnail) VALUES (2, 'WAKE ME UP',  'Beginner', 'Morning', 'https://yoga.com/media/poses/photo/src/up/upward-plank-pose.jpg');
--
--
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (1, 'Downward Dog', 'https://yoga.com/media/cache/e1/6c/e16c631aef1903c2e87570323b2e12fe.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (2, 'Upward Plank', 'https://yoga.com/media/poses/photo/src/up/upward-plank-pose.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (3, 'Low Lunge', 'https://yoga.com/media/poses/photo/src/lo/low-lunge-left-leg-straight.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (4, 'Right Triangle', 'https://yoga.com/media/cache/43/2c/432c86b349511628ddf4cecbb764a49d.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (5, 'Bow Pose', 'https://yoga.com/media/poses/photo/src/bo/bow-pose.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (6, 'Easy Plow Pose', 'https://yoga.com/media/cache/97/b1/97b13ac4e5a0a93e9de4dcfd0528536d.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (7, 'Mountain Pose', 'https://yoga.com/media/cache/10/b0/10b06c949d83ff46d2185b88e72d9b30.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (8, 'Tree Pose', 'http://yogagloble.com/img/720ee90e188c4e4ac35f8b332f904c8d.jpg', 29750, 'https://soundcloud.com/neftaly-ornelas/wake-me-up-avicii-piano-and', '(source: yoga.com)', 2);


-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (15, 'Plank', 'http://media.gettyimages.com/photos/woman-resting-between-poses-in-yoga-class-picture-id583690231?s=170667a', 60714, 'https://soundcloud.com/simon_ekstrom/wake-me-up-avicii-by-avicii', 'GETTY IMAGES', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (16, 'Lunge', 'http://media.gettyimages.com/photos/young-woman-practicing-yoga-in-an-urban-loft-picture-id613013678?s=170667a', 60714, 'https://soundcloud.com/simon_ekstrom/wake-me-up-avicii-by-avicii', 'GETTY IMAGES', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (17, 'High Lunge', 'http://media.gettyimages.com/photos/yoga-teacher-high-lunge-variation-picture-id459093133?s=170667a', 60714, 'https://soundcloud.com/simon_ekstrom/wake-me-up-avicii-by-avicii', 'GETTY IMAGES', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (18, 'Backbend', 'http://media.gettyimages.com/photos/young-woman-practicing-yoga-in-urban-loft-upward-bow-pose-picture-id619089076?s=170667a', 60714, 'https://soundcloud.com/simon_ekstrom/wake-me-up-avicii-by-avicii', 'GETTY IMAGES', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (19, 'Upward Facing Dog', 'http://media.gettyimages.com/photos/young-woman-practicing-yoga-in-urban-loft-upward-facing-dog-picture-id619088918?s=170667a', 60714, 'https://soundcloud.com/simon_ekstrom/wake-me-up-avicii-by-avicii',  'GETTY IMAGES', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (20, 'Crane', 'http://media.gettyimages.com/photos/young-woman-doing-yoga-meditation-and-stretching-exercises-picture-id508540526?s=170667a', 60714, 'https://soundcloud.com/simon_ekstrom/wake-me-up-avicii-by-avicii', 'GETTY IMAGES', 2);
--
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (21, 'Half Lord Of The Fishes', 'http://media.gettyimages.com/photos/ardha-matsyendrasanahalf-lord-of-the-fishes-pose-picture-id459093145?s=170667a', 60714, 'https://soundcloud.com/simon_ekstrom/wake-me-up-avicii-by-avicii', 'GETTY IMAGES', 2);



-- -- Flow with Sia / Song: Cheap Thrills -- Dropped
-- INSERT INTO routines (id, title, level, session, thumbnail) VALUES (2, 'Flow With Sia', 'EXPERT', 'Morning', 'https://unsplash.com/search/yoga?photo=coiWR0gT8Cw');
--
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (20, 'Right Knee To Chest', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDtuE_ht-MgVBjVXnDO1h18FSULiXts1KRfeblJ_bhNhpnnVoXYM5zYogUiO1BjhjYJvbvGbvZPH7fOt7ANbInsG_OzO3FwyNA-JNo4Jca0KmwG8OkYuHZOr4b2IFsspafymzHtnCwjxaiM0Ex62IcUFSyrZMqen5WlfWivOKQ/', 37600, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', 'ROMANBURRI PHOTOGRAPHY (source: NatGeo)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (21, 'Left Knee To Chest', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDth4jOkbbBbVg_OVhRaI4GCzCQqrZ9foypis2kMA-Wya_V_lt6fqTAwMfN2udDHurCxJ_j4C0yW19XxvLgCik2McuhbnXPnaUT-tgrcK5QW30GKk0mo2_AzqeOc8z7-bE1G7XtMDemft8cQ99CFyYuwDkaLN_Zq5KXAyYFnPQ/', 37600, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', 'MARC HENAUER (source: NatGeo)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (22, 'Forward Fold', 'http://yourshot.nationalgeographic.com/u/fQYSUbVfts-T7odkrFJckdiFeHvab0GWOfzhj7tYdC0uglagsDq7mrLLsOeNdP-S7_ULkQ3SxDUPK2ulMKN-Py6frIiWS0c66D32ZWNYyBr2P_a-5dIsB4P-pL5NMDr7g-huKgJogxYKjDuJZ574CygrPXWr8A_qA_M12ipXWU6txl9Dc63BuWwjUflk3ai6iXcu6eYMB1VVP6oO-oPvvKbXiQ/', 37600, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', 'LIANA MANUKYAN (source: NatGeo)', 2);
-- INSERT INTO moves (id, name, image, milliseconds, audio, image_credit, routine_id) VALUES (24, 'Raised Hands', 'http://www.yoganonymous.com/system/posts/thumbnail_images/000/066/007/original/beach_yoga_sequence.jpg?1470674648', 37600, 'https://soundcloud.com/lindimusic1/sia-cheap-trills-ft-sean-paul-lindi-remix', '(source: http://www.yoganonymous.com/)', 2);
